version: '3.8'

services:
  database:
    container_name: database
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: "always"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./data:/var/lib/postgresql/data
    depends_on:
      - database

  symfony:
    container_name: symfony
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
      - database
